[tool.pysen]
version = "0.10.1"

[tool.pysen.lint]
enable_black = false
enable_flake8 = false
enable_isort = false
enable_mypy = true
mypy_preset = "entry"
line_length = 80
py_version = "py38"
mypy_path = ["./stubs"]

[tool.pysen.lint.mypy_modules."torch.*"]
  ignore_errors = true

[[tool.pysen.lint.mypy_targets]]
  paths = ["./example"]
