name: "Nightly CPU Tests"

on:
  schedule:
  - cron: 0 0 * * *
  workflow_dispatch: {}

jobs:
  nightly-test:
    runs-on: ubuntu-22.04
    env:
      JUPYTER_PLATFORM_DIRS: "1"

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Import Check
      run: |
        # Test PPE is importable with minimum dependency
        make import_check-cpu-latest-nightly

    - name: Test CPU only
      run: |
        make cputest-cpu-latest-nightly
