name: "Pre-review Tests"

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        torch: ['1.10.*', '1.11.*', '1.12.*', '1.13.*', '2.0.*']

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - uses: actions/cache@v3
      with:
        path: |
          ~/.cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}-${{ matrix.torch }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Import Check
      run: |
        # Test PPE is importable with minimum dependency
        make import_check-cpu-${${{ matrix.torch }}//\*/\\\\*}-minimal

    - name: Code Style
      run: |
        make lint-cpu-${${{ matrix.torch }}//\*/\\\\*}

    - name: Code Style (Examples)
      run: |
        make example_lint-cpu-${${{ matrix.torch }}//\*/\\\\*}

    - name: Import Check with Extra Package
      run: |
        make import_check-cpu-${${{ matrix.torch }}//\*/\\\\*}

    - name: Test CPU only
      run: |
        make cputest-cpu-${${{ matrix.torch }}//\*/\\\\*}
